/**
 * Author:  Dathriil
 * Created: 09-May-2017
 */

/**
 * Dati accesso DB
 *      username: 'administrator'
 *      password: 'pass'
 */

/**
 * Creazione struttura tabelle
 */

/* User */
CREATE TABLE users (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)     UNIQUE,
    password        VARCHAR(256)    NOT NULL,
    nome            VARCHAR(64),
    cognome         VARCHAR(64),
    dataDiNascita   DATE,
    frase           VARCHAR(1024),
    urlImmagine     VARCHAR(2083)
);

CREATE TABLE friendship (
    follower        INTEGER,
    followed        INTEGER,

    FOREIGN KEY (follower) REFERENCES users(id),
    FOREIGN KEY (followed) REFERENCES users(id),
    PRIMARY KEY (follower, followed)
);

/* Gruppo */
CREATE TABLE gruppi (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(64)     UNIQUE,
    urlImmagine     VARCHAR(2083),
    administrator   INTEGER,

    FOREIGN KEY (administrator) REFERENCES users(id)
);

CREATE TABLE membri_gruppo (
    gruppo          INTEGER,
    membro          INTEGER,

    FOREIGN KEY (gruppo) REFERENCES gruppi(id),
    FOREIGN KEY (membro) REFERENCES users(id),
    PRIMARY KEY (gruppo, membro)
);

/* Post */
CREATE TABLE postType (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(64)     UNIQUE
);

CREATE TABLE posts (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postType        INTEGER         NOT NULL,
    autore          INTEGER         NOT NULL,
    text            VARCHAR(30000),
    content         VARCHAR(2083),
    bacheca_user    INTEGER,
    bacheca_gruppo  INTEGER,

    FOREIGN KEY (postType) REFERENCES postType(id),
    FOREIGN KEY (autore) REFERENCES users(id),
    FOREIGN KEY (bacheca_user) REFERENCES users(id),
    FOREIGN KEY (bacheca_gruppo) REFERENCES gruppi(id)
);

/**
 * Inserimento dati
 */

/* users */
INSERT INTO users (id, username, password, nome, cognome, dataDiNascita, frase, urlImmagine) VALUES
    (1, 'administrator', 'pass', NULL, NULL, NULL, NULL, NULL),
    (default, 'djanni', 'sonodjanni', 'Djanni', 'Randagio', '2011-01-01', 'Datemi cibo! Miao...', 'http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/18160279_1496958173662222_5345517778365317120_n.jpg?ig_cache_key=MTUwMjg0NzcwNzQ1ODY5NzI4Nw%3D%3D.2'),
    (default, 'riccardo', 'ric', 'Riccardo', 'Scateni', '1961-11-06', 'W Oculus Rift!', 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/2/000/10c/3d8/1556a8a.jpg'),
    (default, 'davide', 'ammprogetto', 'Davide', 'Spano', '2011-01-01', 'Do or do not. There is no try.', 'https://i1.rgstatic.net/ii/profile.image/AS%3A278717961130010%401443462948368_l/Lucio_Spano.png'),
    (default, 'incompleto', 'incompleto', NULL, NULL, NULL, NULL, NULL);

/* friendship */
INSERT INTO friendship (follower, followed) VALUES
    (1, 2),
    (2, 1), (2, 3),
    (3, 1), (3, 2),
    (4, 1);

/* gruppi */
INSERT INTO gruppi (id, nome, urlImmagine, administrator) VALUES
    (default, 'Mongolfieristi', 'img/mongolfieristi.png', 3),
    (default, 'Professori', 'img/lucio.bmp', 2),
    (default, 'Animali', 'img/gattodjanni.jpg', 1);

/* membri_gruppo */
INSERT INTO membri_gruppo (gruppo, membro) VALUES
    (1, 1), (1, 3),
    (2, 2), (2, 3),
    (3, 1);

/* postType */
INSERT INTO postType (id, nome) VALUES (1, 'TEXT');
INSERT INTO postType (id, nome) VALUES (2, 'IMAGE');
INSERT INTO postType (id, nome) VALUES (3, 'LINK');

/* post */
INSERT INTO posts (id, postType, autore, text, content, bacheca_user, bacheca_gruppo) VALUES
    (default, 1, 1, 'Ciao, mio schiavo. Dammi cibo! Adesso!', null, 2, null),
    (default, 2, 2, 'Il miglior gatto al mondo.', 'http://scontent.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/18014025_292883181123886_5187515530797383680_n.jpg?ig_cache_key=MTUwMjE2Njg3MzE1MjAyNjU5Mg%3D%3D.2', 1, null),
    (default, 3, 2, 'Ecco un ottimo sito per generare "dummy text".', 'http://www.lipsum.com/', 3, null),
    (default, 3, 2, 'Splendido nuovo modello.', 'http://www.hotairflight.com/wp-content/uploads/2016/08/hot-air-balloon-cost.jpg', null, 1);